# Generated by Django 4.0.3 on 2023-03-07 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phone_nummber',
            new_name='phone_number',
        ),
    ]
