# Generated by Django 4.0.3 on 2023-03-07 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_rename_phone_nummber_customer_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale_record',
            old_name='custom',
            new_name='customer',
        ),
    ]
