# Generated by Django 4.0.3 on 2023-03-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0003_rename_custom_sale_record_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilevo',
            name='for_sale',
            field=models.BooleanField(default=True),
        ),
    ]
